[package]
name = "thanatos"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.29.7"
stdweb = "0.4.20"

[build-dependencies]
winres = "0.1"